config/routes.rb
Prototype::Application.routes.draw do
  get "sessions/new"

  resources :users
  resources :datasets do
    get :duplicate, :on => :member
  end
  resources :messages, :only => [:create, :destroy]
  resources :sessions, :only => [:new, :create, :destroy]
  
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  root :to => "pages#home"

end

app/models/dataset.rb
# == Schema Information
# Schema version: 20101110205939
#
# Table name: datasets
#
#  id            :integer         not null, primary key
#  jobid         :string(255)
#  user_id       :integer
#  person        :string(255)
#  conditions    :string(255)
#  replicate     :string(255)
#  cellType      :string(255)
#  factor        :string(255)
#  numReads      :decimal(, )
#  mappedReads   :decimal(, )
#  unmappedReads :decimal(, )
#  averageCPL    :decimal(, )
#  medianCPL     :decimal(, )
#  minCPL        :decimal(, )
#  maxCPL        :decimal(, )
#  aligner       :string(255)
#  system        :string(255)
#  alignParams   :string(255)
#  refGenome     :string(255)
#  files         :text
#  filesURL      :text
#  sequencer     :string(255)
#  barcode       :string(255)
#  dateDone      :date
#  dateRec       :date
#  lanes         :decimal(, )
#  comments      :text
#  otherInfo     :string(255)
#  created_at    :datetime
#  updated_at    :datetime
#

class Dataset < ActiveRecord::Base
  attr_accessible :jobid, :person, :conditions, :replicate, :cellType, :factor, :numReads, :mappedReads, :unmappedReads, :averageCPL, :medianCPL, :minCPL, :maxCPL, :aligner, :system, :alignParams, :refGenome, :files, :sequencer, :barcode, :dateDone, :dateRec, :lanes, :comments, :otherInfo, :filesURL
  
  belongs_to :user
  has_many :messages
  
  validates :jobid,   :presence => true,
                      :uniqueness => { :case_sensitive => false}
  validates :user_id, :presence => true
  
  #default_scope :order => 'datasets.jobid DESC'
  
  def self.search(search)
    if search
      find(:all, :conditions => ['comments LIKE ?', "%#{search}%"])
    else
      find(:all)
    end    
  end
end

app/controllers/datasets_controller.rb
class DatasetsController < ApplicationController
  before_filter :authenticate, :only => [:index, :edit, :update, :destroy]

  def create
    @dataset = current_user.datasets.build(params[:dataset])
    if @dataset.save
      flash[:success] = "Dataset created!"
      redirect_to datasets_path
    else
      @feed_items = []
      render 'pages/home'
    end
  end

  def destroy
    Dataset.find(params[:id]).destroy
    flash[:success] = "Dataset deleted."
    redirect_to :back
  end
  
  def show
    @dataset = Dataset.find(params[:id])
    @messages = @dataset.messages
    @message = Message.new
    @title = @dataset.id
    @showAll = toggle_state;
  end
  
  def index
    @title = "All datasets"
    #@datasets = Dataset.paginate(:page => params[:page])
    @datasets = Dataset.order(sort_column + " " + sort_direction).search(params[:search])
    @showAll = toggle_state;
  end
  
  def edit
    @dataset = Dataset.find(params[:id])
    @title = "Edit dataset"
  end
  
  def update
    @dataset = Dataset.find(params[:id])
    if @dataset.update_attributes(params[:dataset])
      flash[:success] = "Dataset updated!"
      redirect_to datasets_path
    else
      @title = "Edit dataset"
      render 'edit'
    end
  end
  
  def duplicate
    @dataset = Dataset.find(params[:id])
    @newdataset = Dataset.new(@dataset.attributes)  
    @newdataset.jobid = @newdataset.jobid + " copy"
    @newdataset.save
    if @newdataset.save
        #redirect_to :action => 'list'
      flash[:success] = "Dataset duplicated!"
      redirect_to edit_dataset_path(@newdataset)
    end
  end
  
  private

    def authorized_user
      @dataset = Dataset.find(params[:id])
      redirect_to dataset_path unless current_user?(@dataset.user)
    end

end

app/views/datasets/_dataset.html.erb
<tr>
  <td class="dataset"
    <span class="stuff" ><%= link_to dataset.jobid, {:controller => "datasets", :action => "show", :id => dataset.id, :sort => sort_column, :direction => sort_direction, :showAll => toggle_state} %> </span>
  </td>
  <td class="dataset"
    <span class="stuff" ><%= dataset.person %> </span>
  </td>
  <td class="dataset"
      <span class="stuff"><%= dataset.conditions %> </span>
  </td>
  
  <% if @showAll == "yes"%>
    <td class="dataset"
      <span class="stuff"><%= dataset.replicate %> </span>
    </td>
    <td class="dataset"
      <span class="stuff"><%= dataset.cellType %> </span>
    </td>
    <td class="dataset"
      <span class="stuff"><%= dataset.factor %> </span>
    </td>
    <td class="dataset"
      <span class="stuff"><%= dataset.numReads %> </span>
    </td>
    <td class="dataset"
      <span class="stuff"><%= dataset.mappedReads %> </span>
    </td>
    <td class="dataset"
      <span class="stuff"><%= dataset.unmappedReads %> </span>
    </td>
    <td class="dataset"
      <span class="stuff"><%= dataset.averageCPL %> </span>
    </td>
    <td class="dataset"
      <span class="stuff"><%= dataset.medianCPL %> </span>
    </td>
    <td class="dataset"
      <span class="stuff"><%= dataset.minCPL %> </span>
    </td>
    <td class="dataset"
      <span class="stuff"><%= dataset.maxCPL %> </span>
    </td>
    <td class="dataset"
      <span class="stuff"><%= dataset.aligner %> </span>
    </td>
    <td class="dataset"
      <span class="stuff"><%= dataset.system %> </span>
    </td>
    <td class="dataset"
      <span class="stuff"><%= dataset.alignParams %> </span>
    </td>
    <td class="dataset"
      <span class="stuff"><%= dataset.refGenome %> </span>
    </td>
    <td class="dataset"
      <span class="stuff"><%= dataset.files %> </span>
    </td>
    <td class="dataset"
      <span class="stuff"><%= dataset.filesURL %> </span>
    </td>
    <td class="dataset"
      <span class="stuff"><%= dataset.sequencer %> </span>
    </td>
    <td class="dataset"
      <span class="stuff"><%= dataset.barcode %> </span>
    </td>
  <% end %>
  
  <td class="dataset"
     <span class="stuff"><%= dataset.dateDone %> </span>
  </td>
  <td class="dataset"
    <span class="stuff"><%= dataset.dateRec %> </span>
  </td>
  
  <% if @showAll == "yes" %>
    <td class="dataset"
      <span class="stuff"><%= dataset.lanes %> </span>
    </td>
    <td class="dataset"
      <span class="stuff"><%= dataset.comments %> </span>
    </td>
    <td class="dataset"
      <span class="stuff"><%= dataset.otherInfo %> </span>
    </td>
  <% end %>
  
  <td>
    <%= link_to "edit", edit_dataset_path(dataset)%>
  </td>
  <td>
    <%= link_to "duplicate", duplicate_dataset_path(dataset)%>
  </td>
  <td>
    <%= link_to "delete", dataset, :method => :delete,
                                     :confirm => "Are you sure?",
                                     :title => dataset.jobid %>
  </td>
</tr>

app/views/datasets/edit.html.erb
<h1>Edit dataset</h1>

<%= form_for(@dataset) do |f| %>
  <%= render '/shared/dataset_form', :f => f %>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/datasets/index.html.erb
<h1> All datasets </h1>
<p>
  <table>
    <tr>
      <td>
        <%= render '/shared/dataset_pre_header' %>
      </td>
      <td align="right">
        <% form_tag datasets_path, :method => 'get' do %>
          <p>
            <%= text_field_tag :search, params[:search] %>
            <%= submit_tag "Search comments", :name => nil%>
          </p>
        <% end %>
      </td>
    </tr>
  </table> 
  <div class="datasetTable" style = "overflow-x:auto">  
  <table class="profile">
    <%= render '/shared/dataset_headers' %>
    <%= render @datasets %>
    </table>
  </div>
</p>

app/views/datasets/show.html.erb
<h1><%= @dataset.jobid %></h1>
<p>
  <%= render '/shared/dataset_pre_header' %>
</p>
<div class="datasetTable" style = "overflow-x:auto">  
  <table class="profile" summary="One dataset">
    <%= render '/shared/dataset_headers' %>
    <%= render @dataset %>
  </table>
</div>

<% unless @dataset.messages.empty? %>
  <table class="datasetTable" summary="Dataset messages">
    <%= render @messages %>
  </table>
<% end %>

<p>
  <%= form_for @messages do |f| %>
    <%= render 'shared/error_messages', :comment => f.object %>
    <div class="field">
      <%= f.text_area :comment %>
    </div>
    <div class="actions">
      <%= f.submit "Submit" %>
    </div>
  <% end %>

</p>