config/routes.rb
Prototype::Application.routes.draw do
  get "sessions/new"

  resources :users
  resources :datasets do
    get :duplicate, :on => :member
  end
  resources :messages, :only => [:create, :destroy]
  resources :sessions, :only => [:new, :create, :destroy]
  
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  root :to => "pages#home"

end

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>
  The <a href="http://fg.cns.utexas.edu">Functional Genomics Research Stream</a> is part of the <a href="http://fri.cns.utexas.edu">Freshman Research Initiative</a> at the <a href="http://www.utexas.edu">University of Texas at Austin</a>.
  </br>
  </br>
  This website was developed using Ruby on Rails 3.0 around code provided by <a href="https://github.com/mhartl">Michael Hartl</a>.
  <pre class="verbatim"> 
   Permission is hereby granted, free of charge, to any person
   obtaining a copy of this software and associated documentation
   files (the &quot;Software&quot;), to deal in the Software without
   restriction, including without limitation the rights to use,
   copy, modify, merge, publish, distribute, sublicense, and/or sell
   copies of the Software, and to permit persons to whom the
   Software is furnished to do so, subject to the following
   conditions:
 
   The above copyright notice and this permission notice shall be
   included in all copies or substantial portions of the Software.
 
   THE SOFTWARE IS PROVIDED &quot;AS IS&quot;, WITHOUT WARRANTY OF ANY KIND,
   EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
   OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
   NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
   HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
   WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
   FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
   OTHER DEALINGS IN THE SOFTWARE.</pre> 
</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>
  Please contact 
  <a href="http://fg.cns.utexas.edu">Dr. Patrick Killion</a>.
</p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>
  This page coming soon... For now, please look at the
  <a href="http://fg.cns.utexas.edu">FG website</a>.
</p>

app/views/pages/home.html.erb
<% if signed_in? %>
  <table class="front" summary="For signed-in users">
    <tr>
      <td class="main">
        <h1 class="dataset">Enter a new dataset:</h1>
        <br />

        <%= form_for(@dataset) do |f| %>
          <%= render '/shared/dataset_form', :f => f %>
          <div class = "actions">
            <%= f.submit "Submit" %>
          </div>
        <% end %>

        
      </td>
      <td class="sidebar round">
        <%= render 'shared/user_info' %>
      </td>
    </tr>
  </table>
<% else %>
  <h1>Prototype</h1>

  <p>
    The home page for the future Longhorn Sequencing Database.
  </p>

  <%= link_to "Sign in", signin_path, :class => "signup_button round" %>
  <center>Or <%= link_to "create a new account", signup_path %> </center>
<% end %>